#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "${{ secrets.DATABASE_NAME }}"
database_id = "${{ secrets.DATABASE_ID }}"

[[r2_buckets]]
binding = "R2"
bucket_name = "${{ secrets.BUCKET_NAME }}"

[vars]
R2_PUBLIC_URL = "${{ secrets.PUBLIC_URL }}"

[dev]
port = 5000
